# Generated by Django 2.2.28 on 2023-04-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaInfo',
            fields=[
                ('tweet_id', models.TextField(primary_key=True, serialize=False)),
                ('tweet_user', models.TextField()),
                ('tweet_alpha', models.TextField()),
                ('tweet_text', models.TextField()),
                ('tweet_media', models.TextField()),
                ('tweet_gpt', models.TextField()),
                ('alpha_time', models.TextField()),
                ('user_thumb', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('FollowedToday', models.TextField()),
                ('Followers', models.TextField()),
                ('Bio', models.TextField()),
                ('Created', models.TextField()),
                ('DiscoveryTime', models.TextField()),
            ],
        ),
    ]
